// Auto-generated by sync-contracts.js - DO NOT EDIT
// Last updated: 2025-06-17T07:02:58.510Z
// Chain ID: 11155931 (RISE Testnet)

// Import ABIs
import ChatAppABI from './abi/ChatApp.json';
import TokenLaunchpadABI from './abi/TokenLaunchpad.json';
import FrenPetABI from './abi/FrenPet.json';

export const contracts = {
  ChatApp: {
    address: '0x309bbe8e4745b0c832ac25183f633973aa8e2fd5' as const,
    deploymentTxHash: '0x210e72b0922923beba0302d4378e529f8321184eec752392e8b2a753add789ab',
    blockNumber: 0xe5b8a9,
    abi: ChatAppABI
  },
  TokenLaunchpad: {
    address: '0x094ea1ee17138f69c46ad9bb262c0e6d810b9a48' as const,
    deploymentTxHash: '0x826f1aba142854b8f08af7025c37eccc2d8bbefbf9c7ba3874259ee4dc73531f',
    blockNumber: 0xe5b8aa,
    abi: TokenLaunchpadABI
  },
  FrenPet: {
    address: '0x393224f1c13329b39a33e65121c861a3dae539fc' as const,
    deploymentTxHash: '0xd96c50604c5ceae65c71f5a30f07ed3c967596b49b6a668d52aa2e769630a33f',
    blockNumber: 0xe5b8aa,
    abi: FrenPetABI
  }
} as const;

// Type exports
export type ContractName = keyof typeof contracts;
export type Contracts = typeof contracts;

// Helper functions
export function getContract<T extends ContractName>(name: T): Contracts[T] {
  return contracts[name];
}

export function getContractAddress(name: ContractName): string {
  return contracts[name].address;
}

export function getContractABI(name: ContractName) {
  return contracts[name].abi;
}

// Re-export specific contracts for convenience
export const CHATAPP_ADDRESS = '0x309bbe8e4745b0c832ac25183f633973aa8e2fd5' as const;
export const CHATAPP_ABI = ChatAppABI;
export const TOKENLAUNCHPAD_ADDRESS = '0x094ea1ee17138f69c46ad9bb262c0e6d810b9a48' as const;
export const TOKENLAUNCHPAD_ABI = TokenLaunchpadABI;
export const FRENPET_ADDRESS = '0x393224f1c13329b39a33e65121c861a3dae539fc' as const;
export const FRENPET_ABI = FrenPetABI;
