// Auto-generated by sync-contracts.js - DO NOT EDIT
// Last updated: 2025-06-18T04:19:27.771Z
// Chain ID: 11155931 (RISE Testnet)

// Import ABIs
import ChatAppABI from './abi/ChatApp.json';
import TokenLaunchpadABI from './abi/TokenLaunchpad.json';
import FrenPetABI from './abi/FrenPet.json';

export const contracts = {
  ChatApp: {
    address: '0xcf7b7f03188f3b248d6a3d4bd589dc7c31b55084' as const,
    deploymentTxHash: '0xaa54b83133294bcdabb7ef2f12e2728494a2c4a005cf78948fa14ffbe2181033',
    blockNumber: 0xe6e3d6,
    abi: ChatAppABI
  },
  TokenLaunchpad: {
    address: '0xbf6bd47e8563f24614a75a5755f055edc9ce1b13' as const,
    deploymentTxHash: '0x465a19f718098c431905a2a0758df2cf6f14e96988a6b22b496e4ccd57e2bfa8',
    blockNumber: 0xe6e3d6,
    abi: TokenLaunchpadABI
  },
  FrenPet: {
    address: '0x2d222d701b29e9d8652bb9afee0a1dabdad0bc23' as const,
    deploymentTxHash: '0x13de2689b9f60310291062aa031a85f379defe1003a0921180a941a7a165dc55',
    blockNumber: 0xe6e3d6,
    abi: FrenPetABI
  }
} as const;

// Type exports
export type ContractName = keyof typeof contracts;
export type Contracts = typeof contracts;

// Helper functions
export function getContract<T extends ContractName>(name: T): Contracts[T] {
  return contracts[name];
}

export function getContractAddress(name: ContractName): string {
  return contracts[name].address;
}

export function getContractABI(name: ContractName) {
  return contracts[name].abi;
}

// Re-export specific contracts for convenience
export const CHATAPP_ADDRESS = '0xcf7b7f03188f3b248d6a3d4bd589dc7c31b55084' as const;
export const CHATAPP_ABI = ChatAppABI;
export const TOKENLAUNCHPAD_ADDRESS = '0xbf6bd47e8563f24614a75a5755f055edc9ce1b13' as const;
export const TOKENLAUNCHPAD_ABI = TokenLaunchpadABI;
export const FRENPET_ADDRESS = '0x2d222d701b29e9d8652bb9afee0a1dabdad0bc23' as const;
export const FRENPET_ABI = FrenPetABI;
