// Auto-generated by sync-contracts.js - DO NOT EDIT
// Last updated: 2025-06-04T09:51:56.466Z
// Chain ID: 11155931 (RISE Testnet)

// Import ABIs
import ChatAppABI from './abi/ChatApp.json';

export const contracts = {
  ChatApp: {
    address: '0xa7ca09d052d7e259ac5178fa0ec99b5a49dd44b5' as const,
    deploymentTxHash: '0xaec0c71002b6de0aae7e30cad649b27c37409476e68fbc33537fae35374889ec',
    blockNumber: 0xd4bcc5,
    abi: ChatAppABI
  }
} as const;

// Type exports
export type ContractName = keyof typeof contracts;
export type Contracts = typeof contracts;

// Helper functions
export function getContract<T extends ContractName>(name: T): Contracts[T] {
  return contracts[name];
}

export function getContractAddress(name: ContractName): string {
  return contracts[name].address;
}

export function getContractABI(name: ContractName) {
  return contracts[name].abi;
}

// Re-export specific contracts for convenience
export const CHATAPP_ADDRESS = '0xa7ca09d052d7e259ac5178fa0ec99b5a49dd44b5' as const;
export const CHATAPP_ABI = ChatAppABI;
