// Auto-generated by sync-contracts.js - DO NOT EDIT
// Last updated: 2025-06-17T15:58:51.668Z

import { RISE_CHAIN_ID, RISE_RPC_URL, RISE_WS_URL, RISE_EXPLORER_URL } from '@/config/chain';

// Re-export for backward compatibility
export { RISE_CHAIN_ID, RISE_RPC_URL, RISE_WS_URL, RISE_EXPLORER_URL };

// Contract addresses for WebSocket subscriptions
export const CONTRACTS = {
  "ChatApp": "0x2fd08ac0d7184ae96d50565ec30059009e0d998f"
} as const;

// Re-export specific contract addresses
export const CHATAPP_ADDRESS = '0x2fd08ac0d7184ae96d50565ec30059009e0d998f' as const;
