// Auto-generated by sync-contracts.js - DO NOT EDIT
// Last updated: 2025-06-04T09:51:56.467Z

import { RISE_CHAIN_ID, RISE_RPC_URL, RISE_WS_URL, RISE_EXPLORER_URL } from '@/config/chain';

// Re-export for backward compatibility
export { RISE_CHAIN_ID, RISE_RPC_URL, RISE_WS_URL, RISE_EXPLORER_URL };

// Contract addresses for WebSocket subscriptions
export const CONTRACTS = {
  "ChatApp": "0xa7ca09d052d7e259ac5178fa0ec99b5a49dd44b5"
} as const;

// Re-export specific contract addresses
export const CHATAPP_ADDRESS = '0xa7ca09d052d7e259ac5178fa0ec99b5a49dd44b5' as const;
