// Auto-generated by sync-contracts.js - DO NOT EDIT
// Last updated: 2025-06-18T04:19:27.772Z

import { RISE_CHAIN_ID, RISE_RPC_URL, RISE_WS_URL, RISE_EXPLORER_URL } from '@/config/chain';

// Re-export for backward compatibility
export { RISE_CHAIN_ID, RISE_RPC_URL, RISE_WS_URL, RISE_EXPLORER_URL };

// Contract addresses for WebSocket subscriptions
export const CONTRACTS = {
  "ChatApp": "0xcf7b7f03188f3b248d6a3d4bd589dc7c31b55084",
  "TokenLaunchpad": "0xbf6bd47e8563f24614a75a5755f055edc9ce1b13",
  "FrenPet": "0x2d222d701b29e9d8652bb9afee0a1dabdad0bc23"
} as const;

// Re-export specific contract addresses
export const CHATAPP_ADDRESS = '0xcf7b7f03188f3b248d6a3d4bd589dc7c31b55084' as const;
export const TOKENLAUNCHPAD_ADDRESS = '0xbf6bd47e8563f24614a75a5755f055edc9ce1b13' as const;
export const FRENPET_ADDRESS = '0x2d222d701b29e9d8652bb9afee0a1dabdad0bc23' as const;
