// Auto-generated by sync-contracts.js - DO NOT EDIT
// Last updated: 2025-06-04T09:51:56.467Z

export const RISE_WS_URL = process.env.NEXT_PUBLIC_RISE_WS_URL || 'wss://testnet.riselabs.xyz/ws';
export const RISE_RPC_URL = process.env.NEXT_PUBLIC_RISE_RPC_URL || 'https://testnet.riselabs.xyz';
export const RISE_CHAIN_ID = 11155931;
export const RISE_EXPLORER_URL = 'https://explorer.testnet.riselabs.xyz';

// Contract addresses for WebSocket subscriptions
export const CONTRACTS = {
  "ChatApp": "0xa7ca09d052d7e259ac5178fa0ec99b5a49dd44b5"
} as const;

// Re-export specific contract addresses
export const CHATAPP_ADDRESS = '0xa7ca09d052d7e259ac5178fa0ec99b5a49dd44b5' as const;
