// This file will be auto-generated by deployment script
// Currently empty for testing deploy-and-sync flow

export const deployedContracts = {} as const;

export type DeployedContracts = typeof deployedContracts;