// Auto-generated by sync-contracts.js - DO NOT EDIT
// Last updated: 2025-06-17T15:58:51.664Z
// Chain ID: 11155931 (RISE Testnet)

// Import ABIs
import ChatAppABI from './abi/ChatApp.json';

export const contracts = {
  ChatApp: {
    address: '0x2fd08ac0d7184ae96d50565ec30059009e0d998f' as const,
    deploymentTxHash: '0x9c81319c76bc6fbee0d2c6a3706af6e766030170e0529a7662068c3e6bb25b21',
    blockNumber: 0xe63645,
    abi: ChatAppABI
  }
} as const;

// Type exports
export type ContractName = keyof typeof contracts;
export type Contracts = typeof contracts;

// Helper functions
export function getContract<T extends ContractName>(name: T): Contracts[T] {
  return contracts[name];
}

export function getContractAddress(name: ContractName): string {
  return contracts[name].address;
}

export function getContractABI(name: ContractName) {
  return contracts[name].abi;
}

// Re-export specific contracts for convenience
export const CHATAPP_ADDRESS = '0x2fd08ac0d7184ae96d50565ec30059009e0d998f' as const;
export const CHATAPP_ABI = ChatAppABI;
