// This file will be auto-generated by sync-contracts.js
// It will contain contract addresses and ABIs after deployment

export const contracts = {
  // Example structure:
  // SimpleStorage: {
  //   address: '0x...' as const,
  //   deploymentTxHash: '0x...',
  //   blockNumber: 0x...,
  //   abi: [...]
  // }
} as const;

// Type exports
export type ContractName = keyof typeof contracts;
export type Contracts = typeof contracts;

// Helper functions
export function getContract<T extends ContractName>(name: T): Contracts[T] {
  return contracts[name];
}

export function getContractAddress(name: ContractName): string {
  return contracts[name].address;
}

export function getContractABI(name: ContractName) {
  return contracts[name].abi;
}